#!/bin/bash
# SMD simualtion 
set -e
rm -rf nohup.*
source ~/src/amber-dev/amber/amber.sh


nstlim=25000000                        # 50 ns
# Set number of atoms to be saved
num_atoms=
export CUDA_VISIBLE_DEVICES='GPU'
#!==============================================================================
# CV 
#!==============================================================================
cat <<EOF > smd.in
!===============================================================================
!  SMD in NVT -- $nstlim * 0.002 ps
!===============================================================================

&cntrl

imin=0,                                        ! No minimization
irest=0,                                       ! This is NOT a restart of an old MD
ntx=1,                                         ! Read velocities
                                         

!PBC                                           ! Constant volume
ntb=1,
ntp=0,

! Temperature control
ntt=3,                                         ! Langevin dynamics
gamma_ln=1.0,                                  ! Friction coefficient (ps^-1)
temp0=303.15,                                  ! Target temperature -- keep it

! Potential energy control
cut=9.0,                                       ! No cutoff, in Angstroms

! MD settings
nstlim=$nstlim,                                ! $nstlim fs  total
dt=0.002,                                      ! time step (ps)
!nscm=1,                                        ! Remove translation and rotation
                                               ! every X steps

! SHAKE
ntc=2,                                         ! Constrain bonds
ntf=2,                                         ! Do not calculate forces of 
                                               ! bonds containing hydrogen


! Control how often information is printed
ntpr=50000,                                     ! Print energies every 100ps
ntwx=5000,                                     ! Print coordinates every 100ps
ntwr=50000,                                    ! Print a restart file every 1ns,
!ntwv=-1

ntxo=2,                                        
ioutfm=1,                                      
ntwprt=$num_atoms

! Wrap coordinates when printing them to the same unit cell
!iwrap=1,


! Restraint options
!ntr=1,                                        ! Positional restraints
nmropt=1,                                      ! NMR restraints
infe=1,                                        ! to activate the ABMD and 
                                               ! related algorithm
/
&smd
 output_file = 'smd.txt'
 output_freq = 5000                            ! 100ps
 cv_file = 'cv-smd.in'
/
&pmd
 output_file = 'pmd.txt'
 output_freq = 50000                           !100 ps, same as coord
 cv_file = 'cv-pmd.in'
/


&wt type='REST', istep1=0, istep2=$nstlim,value1=1.0,value2=1.0 /
&wt type='END' /
DISANG=RST
DUMPAVE=restrains.log
END
EOF
#!===============================================================================
#run

pmemd.cuda -O -i smd.in -o smd.out -p prmtop -c inpcrd.rst7 \
              -r smd.ncrst -inf smd.info -x smd.nc & pid=$! #&> run.log &

echo $pid >> ../tmp 
